server:
  http_port: 8080
  grpc_port: 50051
  internal_ip: "127.0.0.1"

mysql:
  dsn: "root:password@tcp(127.0.0.1:3306)/test_db?parseTime=true"
  max_open_conns: 25
  max_idle_conns: 10

redis:
  addr: "localhost:6379"
  password: "mypass"
  db: 0
  pool_size: 100       # 最大活跃连接数
  min_idle_conns: 20   # 始终保持的最小连接数

jwt:
  secret: "your-very-secure-secret-key" # 建议在生产环境使用更复杂的密钥
  expire: 24

etcd:
  endpoints: ["127.0.0.1:2379"]

#接口限流
rate_limit:
  enable: true
  default: 60
  strategies:
    "/api/v1/user": 100     # 获取用户信息 100次/分
    "/api/v1/login": 5      # 登录 5次/分
    "/graphql": 200         # GraphQL 汇总接口 200次/分

#接口缓存
http_cache:
  enable: true
  user_info_ttl: 300   # 5分钟
  static_data_ttl: 3600 # 1小时